<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4254" started-at="2020-07-07T12:14:55 IST" finished-at="2020-07-07T12:14:59 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4254" started-at="2020-07-07T12:14:55 IST" finished-at="2020-07-07T12:14:59 IST">
      <class name="RestAssured.RestAssured.test_ddt">
        <test-method status="PASS" signature="getData()[pri:0, instance:RestAssured.RestAssured.test_ddt@4b1c1ea0]" name="getData" is-config="true" duration-ms="674" started-at="2020-07-07T12:14:55 IST" finished-at="2020-07-07T12:14:56 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getData -->
        <test-method status="FAIL" signature="Createnewuser_DDT(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:RestAssured.RestAssured.test_ddt@4b1c1ea0]" name="Createnewuser_DDT" duration-ms="2169" started-at="2020-07-07T12:14:56 IST" data-provider="testdata" finished-at="2020-07-07T12:14:58 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[random_xyz]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[string_abx]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[abcxyz@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[male]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[active]]>
              </value>
            </param>
          </params>
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["result"] is not a JSONObject.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["result"] is not a JSONObject.
at org.json.JSONObject.getJSONObject(JSONObject.java:770)
at RestAssured.RestAssured.test_ddt.Createnewuser_DDT(test_ddt.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Createnewuser_DDT -->
        <test-method status="FAIL" signature="Createnewuser_DDT(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:RestAssured.RestAssured.test_ddt@4b1c1ea0]" name="Createnewuser_DDT" duration-ms="559" started-at="2020-07-07T12:14:58 IST" data-provider="testdata" finished-at="2020-07-07T12:14:59 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[random_12345]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[string_6789]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[a123456@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[male]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[inactive]]>
              </value>
            </param>
          </params>
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["result"] is not a JSONObject.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["result"] is not a JSONObject.
at org.json.JSONObject.getJSONObject(JSONObject.java:770)
at RestAssured.RestAssured.test_ddt.Createnewuser_DDT(test_ddt.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Createnewuser_DDT -->
        <test-method status="FAIL" signature="Createnewuser_DDT(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:RestAssured.RestAssured.test_ddt@4b1c1ea0]" name="Createnewuser_DDT" duration-ms="599" started-at="2020-07-07T12:14:59 IST" data-provider="testdata" finished-at="2020-07-07T12:14:59 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[random_2325445]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[string_cxmad]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[randommail@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[male]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[inactive]]>
              </value>
            </param>
          </params>
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["result"] is not a JSONObject.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["result"] is not a JSONObject.
at org.json.JSONObject.getJSONObject(JSONObject.java:770)
at RestAssured.RestAssured.test_ddt.Createnewuser_DDT(test_ddt.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Createnewuser_DDT -->
      </class> <!-- RestAssured.RestAssured.test_ddt -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
